### ISSUE TITLE
winrandom import

### ISSUE THREAD

**Issue by DocBO** [sfbahr/PyCrypto-Wheels#5]
Hi,
thanks for providing binaries. I run into the problem (Python 3.5, 64 bit Arch):

Traceback (most recent call last):
  File "C:/Python/64bit/Python35/Scripts/aes-cp", line 6, in <module>
    from nucosCR import write_to_file, read_from_file, CryptoAESBase, hexdigest,                                                                                                 hexdigest_n, get_crc_from_file
  File "C:\python\64bit\python35\lib\site-packages\nucosCR\__init__.py", line 1,                                                                                                 in <module>
    from .cryptorsabase import CryptoRSABase
  File "C:\python\64bit\python35\lib\site-packages\nucosCR\cryptorsabase.py", li                                                                                                ne 3, in <module>
    from Crypto.PublicKey import RSA
  File "C:\python\64bit\python35\lib\site-packages\Crypto\PublicKey\RSA.py", lin                                                                                                e 78, in <module>
    from Crypto import Random
  File "C:\python\64bit\python35\lib\site-packages\Crypto\Random\__init__.py", l                                                                                                ine 28, in <module>
    from Crypto.Random import OSRNG
  File "C:\python\64bit\python35\lib\site-packages\Crypto\Random\OSRNG\__init__.                                                                                                py", line 34, in <module>
    from Crypto.Random.OSRNG.nt import new
  File "C:\python\64bit\python35\lib\site-packages\Crypto\Random\OSRNG\nt.py", l                                                                                                ine 28, in <module>
    import winrandom
ImportError: No module named 'winrandom'

The bug is known on https://github.com/dlitz/pycrypto/commit/10abfc8633bac653eda4d346fc051b2f07554dcd

I fixed it locally but i was wondering, why this bug appeared again in your dist.

**Comment by sfbahr** [comment]
That's a bug in PyCrypto 2.6. I didn't modify it all just built it. It should be fixed in 2.7a1.
